### ISSUE TITLE
Error. If i Try to Join the Server:

### ISSUE THREAD

**Issue by DrSchnippel** [ZombieStriker/playerlistutil#3]
I get this Error. If i Try to Join the Server:
![Dis-Info](https://user-images.githubusercontent.com/33026764/54764234-ad6b3380-4bf7-11e9-821d-c97ec3ed1e9f.PNG)

My Code: 
`PlayerList list = new PlayerList(ev.getPlayer(),PlayerList.SIZE_DEFAULT);`
` //You can choose any size for this.`
` list.initTable();`
` list.updateSlot(0,"Top left");`
` list.updateSlot(16,"Bottom left");`

No Error in Console. i'm using Spigot 1.13.2

**Comment by DrSchnippel** [comment]
If i Use setHeaderFooter(... so if i Join comes this big Error Log.

[17:58:08 INFO]: Dr_Schnippel[/127.0.0.1:53996] logged in with entity id 5654 at ([world]4832.352103900997, 69.0625, 730.6966944047725)
[17:58:09 INFO]: Dr_Schnippel lost connection: Disconnected
[17:58:09 INFO]: Dr_Schnippel left the game
[17:58:09 INFO]: PLEASE REPORT THIS ISSUE TO ZOMBIE_STRIKER ON THE BUKKIT FORUMS
[17:58:09 WARN]: java.lang.NullPointerException
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.ReflectionUtil.invokeMethod(PlayerList.java:781)
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.PlayerList.getHandle(PlayerList.java:596)
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.PlayerList.sendPacket(PlayerList.java:590)
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.PlayerList.sendNEWTabPackets(PlayerList.java:569)
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.PlayerList.access$600(PlayerList.java:39)
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.PlayerList$1.callBack(PlayerList.java:539)
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.Skin$3$1.run(PlayerList.java:1129)
[17:58:09 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[17:58:09 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
[17:58:09 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
[17:58:09 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[17:58:09 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[17:58:09 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[17:58:09 WARN]:        at java.lang.Thread.run(Unknown Source)
[17:58:09 INFO]: PLEASE REPORT THIS ISSUE TO ZOMBIE_STRIKER ON THE BUKKIT FORUMS
[17:58:09 WARN]: java.lang.NullPointerException
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.ReflectionUtil.invokeMethod(PlayerList.java:781)
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.PlayerList.getHandle(PlayerList.java:596)
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.PlayerList.sendPacket(PlayerList.java:590)
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.PlayerList.sendNEWTabPackets(PlayerList.java:569)
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.PlayerList.access$600(PlayerList.java:39)
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.PlayerList$1.callBack(PlayerList.java:539)
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.Skin$3$1.run(PlayerList.java:1129)
[17:58:09 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[17:58:09 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
[17:58:09 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.PlayerList.access$600(PlayerList.java:39)
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.PlayerList$1.callBack(PlayerList.java:539)
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.Skin$3$1.run(PlayerList.java:1129)
[17:58:09 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[17:58:09 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
[17:58:09 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
[17:58:09 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.PlayerList$1.callBack(PlayerList.java:539)
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.Skin$3$1.run(PlayerList.java:1129)
[17:58:09 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[17:58:09 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
[17:58:09 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
[17:58:09 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[17:58:09 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[17:58:09 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[17:58:09 WARN]:        at java.lang.Thread.run(Unknown Source)
[17:58:09 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
[17:58:09 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
[17:58:09 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[17:58:09 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[17:58:09 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[17:58:09 WARN]:        at java.lang.Thread.run(Unknown Source)
[17:58:09 INFO]: PLEASE REPORT THIS ISSUE TO ZOMBIE_STRIKER ON THE BUKKIT FORUMS
[17:58:09 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
[17:58:09 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[17:58:09 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[17:58:09 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[17:58:09 WARN]:        at java.lang.Thread.run(Unknown Source)
[17:58:09 INFO]: PLEASE REPORT THIS ISSUE TO ZOMBIE_STRIKER ON THE BUKKIT FORUMS
[17:58:09 WARN]: java.lang.NullPointerException
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.ReflectionUtil.invokeMethod(PlayerList.java:781)
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.PlayerList.getHandle(PlayerList.java:596)
[17:58:09 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[17:58:09 WARN]:        at java.lang.Thread.run(Unknown Source)
[17:58:09 INFO]: PLEASE REPORT THIS ISSUE TO ZOMBIE_STRIKER ON THE BUKKIT FORUMS
[17:58:09 WARN]: java.lang.NullPointerException
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.ReflectionUtil.invokeMethod(PlayerList.java:781)
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.PlayerList.getHandle(PlayerList.java:596)
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.PlayerList.sendPacket(PlayerList.java:590)
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.PlayerList.sendNEWTabPackets(PlayerList.java:569)
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.PlayerList.access$600(PlayerList.java:39)
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.PlayerList$1.callBack(PlayerList.java:539)
[17:58:09 WARN]:        at de.dr_schnippel.cyw_wirtschafts_suitev3.helpers.Skin$3$1.run(PlayerList.java:1129)
[17:58:09 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:81)
[17:58:09 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:392)
[17:58:09 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:889)
[17:58:09 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:417)
[17:58:09 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:831)
[17:58:09 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:729)
[17:58:09 WARN]:        at java.lang.Thread.run(Unknown Source)

And one Question: How i can Use Prefixes and Color in the List? 
if I Use Color-Codes or [ & §, Spaces too, so i becomes the Error 

![](https://user-images.githubusercontent.com/33026764/54764234-ad6b3380-4bf7-11e9-821d-c97ec3ed1e9f.PNG)

**Comment by luizhtss** [comment]
I have the same problem.
